export {default as Header} from "./Header";
export {default as Footer} from "./Footer";
export {default as MenuMain} from "./MenuMain";
export {default as Logo} from "./Logo";
export {default as Wrap1200} from "./Wrap1200";
export {default as SocialNetworks} from "./SocialNetworks";
export {default as Title} from "./Title";
export {default as TitleSmall} from "./TitleSmall";
export {default as Map} from "./Map";